### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/infografia-de-hilos-Vanessacruzortiz#2]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Vanessacruzortiz/files/15103036/Infografia.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenas tardes compañera, bien hecho 20 de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
